# Generated by Django 5.2.8 on 2025-12-02 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_body_post_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbookmark',
            name='post',
            field=models.ForeignKey(help_text='The post that was bookmarked.', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks_post', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='postbookmark',
            name='user',
            field=models.ForeignKey(help_text='The user who bookmarked the post.', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
